# Generated by Codex on 2026-07-20

from django.db import migrations, models


DEFAULT_CERTIFICATION_IMAGE_URL = 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=900&q=80'


def add_default_certification_images(apps, _schema_editor):
    CertificationItem = apps.get_model('portfolio_data', 'CertificationItem')

    CertificationItem.objects.filter(
        image='',
        image_url='',
    ).update(
        image_url=DEFAULT_CERTIFICATION_IMAGE_URL,
        image_alt='Certification preview',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_data', '0011_restaurant_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/certifications/'),
        ),
        migrations.AddField(
            model_name='certificationitem',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='certificationitem',
            name='image_alt',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.RunPython(add_default_certification_images, migrations.RunPython.noop),
    ]
