# Generated by Codex on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_data', '0009_experienceitem_projectitem_skillitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('issuer', models.CharField(blank=True, max_length=180)),
                ('issued_date', models.CharField(blank=True, max_length=120)),
                ('credential_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['order', '-id'],
            },
        ),
    ]
