# Generated by Django 4.2.30 on 2026-06-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.JSONField(default=dict)),
                ('about', models.JSONField(default=dict)),
                ('experience', models.JSONField(default=dict)),
                ('skills', models.JSONField(default=dict)),
                ('projects', models.JSONField(default=dict)),
                ('contact', models.JSONField(default=dict)),
                ('footer', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio Configuration',
            },
        ),
    ]
