# Generated by Django 6.0.6 on 2026-07-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_data', '0005_add_section_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioconfig',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/about/'),
        ),
        migrations.AddField(
            model_name='portfolioconfig',
            name='contact_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/contact/'),
        ),
        migrations.AddField(
            model_name='portfolioconfig',
            name='project_1_upload',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/projects/'),
        ),
        migrations.AddField(
            model_name='portfolioconfig',
            name='project_2_upload',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/projects/'),
        ),
        migrations.AddField(
            model_name='portfolioconfig',
            name='project_3_upload',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/projects/'),
        ),
        migrations.AddField(
            model_name='portfolioconfig',
            name='project_4_upload',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/projects/'),
        ),
    ]
