# Generated by Django 6.0.6 on 2026-07-20 09:12

from django.db import migrations, models


RESTAURANT_IMAGE_URL = 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=900&q=80'


def copy_json_items_to_models(apps, _schema_editor):
    PortfolioConfig = apps.get_model('portfolio_data', 'PortfolioConfig')
    ExperienceItem = apps.get_model('portfolio_data', 'ExperienceItem')
    ProjectItem = apps.get_model('portfolio_data', 'ProjectItem')
    SkillItem = apps.get_model('portfolio_data', 'SkillItem')

    config = PortfolioConfig.objects.first()
    if not config:
        return

    if not ExperienceItem.objects.exists():
        for index, item in enumerate((config.experience or {}).get('items', []), start=1):
            role = (item.get('role') or '').strip()
            company = (item.get('company') or '').strip()
            if not role and not company:
                continue
            ExperienceItem.objects.create(
                role=role or 'Experience',
                company=company,
                period=(item.get('period') or '').strip(),
                points='\n'.join(point.strip() for point in item.get('points', []) if point.strip()),
                order=index,
            )

    if not SkillItem.objects.exists():
        for index, item in enumerate((config.skills or {}).get('items', []), start=1):
            name = (item.get('name') or '').strip()
            if not name:
                continue
            SkillItem.objects.create(
                name=name,
                icon=(item.get('icon') or '').strip(),
                order=index,
            )

    if not ProjectItem.objects.exists():
        for index, item in enumerate((config.projects or {}).get('items', []), start=1):
            name = (item.get('name') or '').strip()
            if not name:
                continue
            live_url = (item.get('liveUrl') or '').strip()
            github_url = (item.get('githubUrl') or '').strip()
            ProjectItem.objects.create(
                name=name,
                description=(item.get('description') or '').strip(),
                brief=(item.get('brief') or '').strip(),
                stack=(item.get('stack') or ' | '.join(item.get('tags', []))).strip(),
                live_url='' if live_url == '#' else live_url,
                show_live_url=bool(live_url and live_url != '#'),
                github_url='' if github_url == '#' else github_url,
                show_github_url=bool(github_url and github_url != '#'),
                image_url=(item.get('imageUrl') or '').strip(),
                image_alt=(item.get('imageAlt') or '').strip(),
                order=index,
            )

    if not ProjectItem.objects.filter(name='Restaurant Reservation System').exists():
        ProjectItem.objects.create(
            name='Restaurant Reservation System',
            description='Full-stack restaurant booking app with customer reservations and staff admin dashboard.',
            brief=(
                'A comprehensive full-stack web app to streamline table booking and manage restaurant '
                'reservations. It includes a customer-facing booking interface, an admin dashboard for '
                'staff to oversee reservations, status tracking, real-time table availability management, '
                'secure REST APIs, and JWT authentication for admin access.'
            ),
            stack='React.js | Node.js | Express | PostgreSQL | REST APIs | JWT | Vercel',
            live_url='https://restaurant-reservation-dm6slknqa-manis-projects-b2333fb6.vercel.app/',
            show_live_url=True,
            github_url='',
            show_github_url=False,
            image_url=RESTAURANT_IMAGE_URL,
            image_alt='Restaurant Reservation System preview',
            order=5,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_data', '0008_set_default_social_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=160)),
                ('company', models.CharField(max_length=180)),
                ('period', models.CharField(blank=True, max_length=120)),
                ('points', models.TextField(blank=True, help_text='Write one bullet point per line.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('brief', models.TextField(blank=True)),
                ('stack', models.CharField(blank=True, max_length=240)),
                ('live_url', models.URLField(blank=True)),
                ('show_live_url', models.BooleanField(default=True)),
                ('github_url', models.URLField(blank=True)),
                ('show_github_url', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/projects/')),
                ('image_url', models.URLField(blank=True)),
                ('image_alt', models.CharField(blank=True, max_length=180)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SkillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('icon', models.CharField(blank=True, help_text='Optional Devicon class, for example: devicon-python-plain', max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RunPython(copy_json_items_to_models, migrations.RunPython.noop),
    ]
