# Generated by Codex on 2026-07-20

from django.db import migrations


RESTAURANT_IMAGE_URL = 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=900&q=80'


def add_restaurant_project_image(apps, _schema_editor):
    ProjectItem = apps.get_model('portfolio_data', 'ProjectItem')

    ProjectItem.objects.filter(
        name='Restaurant Reservation System',
        image='',
        image_url='',
    ).update(
        image_url=RESTAURANT_IMAGE_URL,
        image_alt='Restaurant Reservation System preview',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_data', '0010_certifications'),
    ]

    operations = [
        migrations.RunPython(add_restaurant_project_image, migrations.RunPython.noop),
    ]
