# Generated by Django 5.2.17 on 2026-08-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_data', '0012_certification_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioconfig',
            name='notification_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated email addresses to receive contact form notifications.'),
        ),
    ]
