# Generated by Django 6.0.6 on 2026-07-19 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioconfig',
            options={'verbose_name': 'Portfolio Content', 'verbose_name_plural': 'Portfolio Content'},
        ),
    ]
